import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Normal"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000
multiplier = 3

[window.dimensions]
columns = 200
lines = 80

[window.padding]
x = 10
y = 5
